version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - secflowcheck-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U secflowcheck -d secflowcheck_auth_db" ]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: secflowcheck_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - secflowcheck-network
    depends_on:
      - postgres

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - secflowcheck-network

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-pass}
    networks:
      - secflowcheck-network
    depends_on:
      - mongo

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - secflowcheck-network

  rabbitmq:
    image: rabbitmq:3-management
    depends_on:
      - redis
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_DASHBOARD_PORT}:15672"
    networks:
      - secflowcheck-network

  discovery:
    build: ./secflowcheck-discovery
    ports:
      - "${DISCOVERY_PORT}:8761"
    networks:
      - secflowcheck-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1" ]
      interval: 10s
      retries: 10
      start_period: 30s

  gateway:
    build: ./secflowcheck-gateway
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery:8761/eureka/"
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${GATEWAY_PORT}:8080"
    networks:
      - secflowcheck-network

  auth:
    build: ./secflowcheck-authentication
    depends_on:
      discovery:
        condition: service_healthy
      postgres:
        condition: service_healthy
    entrypoint: [ "/wait-for-service.sh", "postgres", "5432" ]
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      EUREKA_SERVER: "http://discovery:8761/eureka"
      ALGORITHM: ${ALGORITHM}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_IP: auth
    ports:
      - "${AUTH_PORT}:8000"
    networks:
      - secflowcheck-network

  parser:
    build: ./secflowcheck-parser
    depends_on:
      discovery:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_SERVER: "http://discovery:8761/eureka"
      INSTANCE_IP: parser
    ports:
      - "${PARSER_PORT}:8001"
    networks:
      - secflowcheck-network

  analyzer:
    build: ./secflowcheck-analyzer
    depends_on:
      rabbitmq:
        condition: service_started
      discovery:
        condition: service_healthy
    environment:
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      REPORT_API_URL: "http://report:8002/reports"
      REPORT_JWT: ${REPORT_JWT}
      DEBUG: ${DEBUG}
      INSTANCE_IP: analyzer
    ports:
      - "${ANALYZER_PORT}:8003"
    networks:
      - secflowcheck-network

  analyzer-worker:
    build: ./secflowcheck-analyzer
    command: celery -A app.celeryconfig.celery_app worker --loglevel=info -Q analysis_queue
    depends_on:
      - rabbitmq
      - analyzer
    environment:
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      REPORT_API_URL: "http://report:8002/reports"
      REPORT_JWT: ${REPORT_JWT}
      DEBUG: ${DEBUG}
    networks:
      - secflowcheck-network

  report:
    build: ./secflowcheck-report
    depends_on:
      mongo:
        condition: service_started
      discovery:
        condition: service_healthy
      analyzer:
        condition: service_started
    entrypoint: [ "/wait-for-service.sh", "mongo", "27017" ] 
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002" ]
    environment:
      PYTHONUNBUFFERED: 1
      MONGO_URI: "mongodb://mongo:27017"
      MONGO_DB: ${MONGO_DB:-secflowcheck_report_db}
      JWT_SECRET: ${JWT_SECRET}
      DEBUG: ${DEBUG}
      API_KEY: ${API_KEY}
      INSTANCE_IP: report
    ports:
      - "${REPORT_PORT}:8002"
    networks:
      - secflowcheck-network

volumes:
  mongo-data:
  postgres-data:
  pgadmin-data:


networks:
  secflowcheck-network:
    driver: bridge
