version: "3.8"

services:
  frontend:
    build:
      context: ./secflowcheck-frontend-v2
      dockerfile: Dockerfile.dev
    volumes:
      - ./secflowcheck-frontend-v2/src:/app/src
      - ./secflowcheck-frontend-v2/components:/app/components
      - ./secflowcheck-frontend-v2/assets:/app/assets
      - ./secflowcheck-frontend-v2/public:/app/public
      - ./secflowcheck-frontend-v2/next.config.mjs:/app/next.config.mjs
      - ./secflowcheck-frontend-v2/tsconfig.json:/app/tsconfig.json
      - ./secflowcheck-frontend-v2/postcss.config.mjs:/app/postcss.config.mjs
      - ./secflowcheck-frontend-v2/package.json:/app/package.json
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev