version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    user: root # Required to access the Docker socket to build images
    ports:
      - "9090:8080" # Modified to 9090 to avoid conflict with Gateway
      - "50000:50000"
    networks:
      - secflowcheck-network
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Docker-in-Docker
    restart: unless-stopped

volumes:
  jenkins_home:

networks:
  secflowcheck-network:
    external: true
